### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Mikeost** [MikeostCorp/Gradify#3]
## TODO list:

- [X] Config file.
- [X] Dark/Light/System UI themes.
- [X] Qss styles.
- [X] New app icon.
- [X] New preloader.
- [X] User Authorization.
- [X] Authorization on server(input fields for any ip, db names e.t.c.)
- [X] SQL Query.
- [X] Report constructor.
- [X] User remembering during authorization
- [X] Separate forms for editing posts
- [X] Filter buttons in the table
- [X] Ability to save the report in .pdf and .html format, with a choice of saving path
- [x] Search bar on the table
- [X] Change the delete-row window
- [X] Data statistics with graphs and diagrams
- [X] Statistics for each table
- [X] App user guide
- [X] Table Export

## Bug report:
- [X] Tables stop loading after a minute of inactivity :/
- [X] (Only on OSX 10.15). Sometimes after restarting appears "ghost" logged user and causes an error[segfault]
- [x] "customWidgets" folder does not appear in ui_* files 6685947

## Ideas for future updates:
- [x] ~~Write unit tests~~ / Build a CI/CD pipeline(Github Actions).
- [ ] Review application architecture:
    - [x] Database refactoring. (MySQL -> Firebase)
    - [ ] Separation of Configuration (secret data like a logins, passwords, IP addresses should not be stored in the code).
    - [ ] Password hashing
    - [ ] Code refactoring (data structures and algorithms, data transfer between database and forms).
- [ ] Reworking the appearance of the application:
    - [ ] Make it possible to scroll the left menu of the main window.
    - [ ] Transferring icons from png to svg format.
    - [ ] Update main app icon.
- [ ] Features: 
    - [ ] Add a language changer to the application settings.
    - [ ] Add and edit photos of people for the forms for editing table entries (maybe url-links in "Student" table).
- [ ] Docs:
    - [ ] English versions of er-diagrams and user guide

**Comment by AndriiBash** [comment]
Assume!
